name: 'Update Algolia Index'
description: 'Update Algolia Index'
inputs:
  docs_type:
    description: 'Docs Type'
    required: true

  docs_version:
    description: 'Docs Version'
    required: true

outputs:
  result:
    description: 'Result'
    value: '{}'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade pipenv wheel
        cd ${{ github.action_path }}
        pipenv install --keep-outdated
        pipenv run python -m src.index config ${{ inputs.docs_type }} ${{ inputs.docs_version }}
