name: 'Update Algolia Index'
description: 'Update Algolia Index'
inputs:
  docs_type:
    description: 'Docs Type'
    required: true

  docs_version:
    description: 'Docs Version'
    required: true

outputs:
  result:
    description: 'Result'
    value: '{}'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade pipenv==2024.2.0 wheel
        cd ${{ github.action_path }}
        pipenv install
        pipenv run python -m src.index ${{ inputs.docs_type }} ${{ inputs.docs_version }}
